"""Initial

Revision ID: da3e04a7ef01
Revises: 503238d0e55b
Create Date: 2022-07-14 16:24:38.264764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3e04a7ef01'
down_revision = '503238d0e55b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
